#ifndef PSVM_PSVMJS_HPP
#define PSVM_PSVMJS_HPP

#include <inttypes.h>

// Wrapper namespace for the C source generated by qjsc
namespace psvmjs {
    extern "C" {

#include "psvmjs.c"

    };
}

#endif //PSVM_PSVMJS_HPP
