#ifndef PSVM_H
#define PSVM_H

#include <iostream>
#include <functional>

#include "quickjs-libc.h"
#include "psvm-js.h" // generated by qjsc at build

class ShowdownSimulator{
    public:
        ShowdownSimulator();
        ~ShowdownSimulator();
    
    private:
        
}

#endif