#include <stdio.h>
#include <string.h>

#include "quickjs-libc.h"
#include "psvm-js.h" // generated by qjsc at build

JSValue OnSimulatorResponse(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
  // Check the number of arguments
  if (argc != 1)
  {
    return JS_ThrowTypeError(ctx, "OnSimulatorResponse() expects 1 argument");
  }

  // Convert the JavaScript string to a C string
  const char *c_str = JS_ToCString(ctx, argv[0]);
  if (!c_str)
  {
    return JS_EXCEPTION;
  }

  // placeholder, todo replace with actual fn
  puts(c_str);

  // Free the C string when you're done
  JS_FreeCString(ctx, c_str);

  return JS_UNDEFINED;
}

static JSContext *JS_NewCustomContext(JSRuntime *rt)
{
  JSContext *ctx = JS_NewContextRaw(rt);
  if (!ctx)
    return NULL;
  JS_AddIntrinsicBaseObjects(ctx);
  JS_AddIntrinsicDate(ctx);
  JS_AddIntrinsicEval(ctx);
  JS_AddIntrinsicStringNormalize(ctx);
  JS_AddIntrinsicRegExp(ctx);
  JS_AddIntrinsicJSON(ctx);
  JS_AddIntrinsicProxy(ctx);
  JS_AddIntrinsicMapSet(ctx);
  JS_AddIntrinsicTypedArrays(ctx);
  JS_AddIntrinsicPromise(ctx);
  JS_AddIntrinsicBigInt(ctx);
  js_std_eval_binary(ctx, qjsc_psvm, qjsc_psvm_size, 0);
  js_std_eval_binary(ctx, qjsc_globalize, qjsc_globalize_size, 0);

  // custom handler
  JSValue global_obj = JS_GetGlobalObject(ctx);

  JSValue host = JS_NewObject(ctx);
  JS_SetPropertyStr(ctx, global_obj, "host", host);
  JS_SetPropertyStr(ctx, host, "OnSimulatorResponse", JS_NewCFunction(ctx, OnSimulatorResponse, "OnSimulatorResponse", 1));

  JS_FreeValue(ctx, global_obj);

  return ctx;
}

char *const createSim = "\
globalThis.SimulatorInstance = new psvm.ShowdownSimulator();\n\
SimulatorInstance.onResponseOmniscient = (chunk) => host.OnSimulatorResponse(chunk);\n";

char *const testCode = "\
  var lines = [\
  `>start {\"formatid\":\"gen9customgame\"}`,\n\
  `>player p1 {\"name\":\"Bot 1\",\"team\":\"Samurott||AssaultVest|Torrent|knockoff,flipturn,grassknot,hydropump||85,85,85,85,85,85||||88|,,,,,Dark]Azumarill||SitrusBerry|HugePower|liquidation,aquajet,playrough,bellydrum||85,85,85,85,85,85||||82|,,,,,Water]Meowscarada||ChoiceBand|Protean|knockoff,playrough,flowertrick,uturn||85,85,85,85,85,85||||78|,,,,,Grass]Iron Valiant||LifeOrb|QuarkDrive|swordsdance,spiritbreak,knockoff,closecombat||85,85,85,85,85,85|N|||79|,,,,,Fighting]Clodsire||Leftovers|Unaware|recover,curse,earthquake,gunkshot||85,85,85,85,85,85||||81|,,,,,Ground]Ampharos||ChoiceSpecs|Static|focusblast,voltswitch,thunderbolt,dazzlinggleam||85,,85,85,85,85||,0,,,,||88|,,,,,Fairy\"}`,\n \
  `>player p2 {\"name\":\"Bot 2\",\"team\":\"Jolteon||Leftovers|VoltAbsorb|substitute,terablast,calmmind,thunderbolt||85,,85,85,85,85||,0,,,,||84|,,,,,Ice]Greedent||SitrusBerry|CheekPouch|bodyslam,earthquake,psychicfangs,swordsdance||85,85,85,85,85,85||||87|,,,,,Psychic]Lurantis||Leftovers|Contrary|knockoff,leafstorm,synthesis,superpower||85,85,85,85,85,85||||91|,,,,,Fighting]Polteageist||WhiteHerb|CursedBody|shadowball,storedpower,gigadrain,shellsmash||85,,85,85,85,85|N|,0,,,,||79|,,,,,Psychic]Gurdurr||Eviolite|Guts|drainpunch,knockoff,machpunch,bulkup||85,85,85,85,85,85||||85|,,,,,Steel]Glastrier||ChoiceBand|ChillingNeigh|iciclecrash,highhorsepower,closecombat,heavyslam||81,85,85,85,85,85|N|||86|,,,,,Fighting\"}`\n\
    ];\n \
  lines.forEach( (line) => void SimulatorInstance.writeToOmniscient(line) );";

int main(int argc, char **argv)
{
  JSRuntime *rt;
  JSContext *ctx;
  rt = JS_NewRuntime();
  js_std_set_worker_new_context_func(JS_NewCustomContext);
  js_std_init_handlers(rt);
  JS_SetModuleLoaderFunc(rt, NULL, js_module_loader, NULL);
  ctx = JS_NewCustomContext(rt);
  js_std_add_helpers(ctx, argc, argv);

  JS_Eval(ctx, createSim, strlen(createSim), "<module>", JS_EVAL_TYPE_MODULE);
  JS_Eval(ctx, testCode, strlen(testCode), "<module>", JS_EVAL_TYPE_MODULE);

  js_std_loop(ctx);
  JS_FreeContext(ctx);
  JS_FreeRuntime(rt);
  return 0;
}